# Generated by Django 3.2.5 on 2022-08-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profilepic.png', upload_to='profile_pictures'),
        ),
    ]
